title: LEDs, buzzers and Scratch games
hero_image: images/banner.png
description: leds-buzzers-scratch-games description
version: 4
listed: false
copyedit: false
last_tested: "2019-10-22"
steps:
  - title: Introduction
  - title: Lighting an LED
  - title: Coding an LED using an I/O pin
  - title: Making noise with buzzers
  - title: Coding sequences
  - title: Scratch, sound and lights
  - title: Scratch games with LEDs and buzzers
  - title: Think big!
  - title: What next?
